server.port: 9000
server.use-forward-headers=true

oauth:
    google:
        callback: http://amauta.lamolina.edu.pe/callback
        key: 612109039547-kpslatsrvja8s3ftl9ll2bcncjl9p7dc.apps.googleusercontent.com
        secret: i_Eh3sJ3yB9ujG9wZeXXQdJD


persistence:
    jdbcUrl: jdbc:mysql://bagre.albatross.pe/lamolina?autoReconnect=true&useSSL=false
    userdb: thor
    password: redhotchimichurri
    showSql: false


despliegue:
    prospecto: prospecto2017g
    activo: false
    emails: lypagl@gmail.com
    copias: lypagl@gmail.com
    mailer: false
    lagunas: true
    s3: true
    tawkto: false
    sistema: 3

logging.file: /var/log/jenkins/lamolina-pivot.log
logging.level.pe.edu.lamolina: DEBUG
#logging.level.pe.albatross.octavia: DEBUG

#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
