server.port: 9000
server.use-forward-headers=true

oauth:
    google:
        callback: http://amauta.albatross.pe/callback
        key: 612109039547-kpslatsrvja8s3ftl9ll2bcncjl9p7dc.apps.googleusercontent.com
        secret: i_Eh3sJ3yB9ujG9wZeXXQdJD


persistence:
    jdbcUrl: jdbc:mysql://localhost/agraria?autoReconnect=true&useSSL=false
    userdb: root
    password: mysql
    showSql: false


despliegue:
    activo: false
    mailer: false


logging.file: /var/log/jenkins/lamolina-pivot.log
logging.level.pe.edu.lamolina: DEBUG
