server.port: 9900
server.session.timeout: 7200


oauth:
    google:
        api: pe.albatross.zelpers.security.oauth.Google2Api
        callback: http://localhost:9900/callback
        key: 612109039547-a2nrlbq1s4cheeabprtb2hb1odkodcur.apps.googleusercontent.com
        secret: zAG0isrqVamwwRRlSjzx_SEi


spring.thymeleaf.prefix: /WEB-INF/
spring.thymeleaf.cache: false


persistence:
    driver: com.mysql.jdbc.Driver
    dialect: org.hibernate.dialect.MySQLDialect
    jdbcUrl: jdbc:mysql://localhost/agraria
    userdb: root
    password: mysql
    showSql: true
    model: pe.edu.lamolina.pivot


task:
    corePoolSize: 3
    threadName: Spring-Task-


error:
    whitelabel:
        enabled: false


multipart.maxFileSize: 80MB
multipart.maxRequestSize: 80MB


logging.level.org.springframework.web: INFO
logging.level.org.hibernate: INFO
logging.level.pe.edu.lamolina: DEBUG


despliegue:
    activo:  false
    netsuite: false
    powerschool: false
    xtend: false
    mailer: false


spring.redis.host: localhost
spring.redis.port: 6379
