server.port: 443

server.ssl.key-store: /lost+found/certificados/lamolina.store
server.ssl.key-store-password: z3pp3l1n
server.ssl.keyAlias: lamolina2018


#oauth:
#    google:
#        callback: https://amauta-test.lamolina.edu.pe/callback
#        key: 1098804607809-f8a85cpqdrvn7lajb7v5a1lucuegdst2.apps.googleusercontent.com
#        secret: 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

# Google OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id: 1098804607809-f8a85cpqdrvn7lajb7v5a1lucuegdst2.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret: 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
spring.security.oauth2.client.registration.google.redirect-uri: https://amauta-test.lamolina.edu.pe/callback
spring.security.oauth2.client.registration.google.scope: email,profile

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://openidconnect.googleapis.com/v1/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=email

# Microsoft Configuration
spring.security.oauth2.client.registration.microsoft.client-id=a3b886dd-e5bd-4ff1-8a6a-59eb212168be
spring.security.oauth2.client.registration.microsoft.client-secret=Fpc8Q~.CHQIqmKgntflk415LnwktdesrOmprub29
spring.security.oauth2.client.registration.microsoft.scope=openid,email,profile
spring.security.oauth2.client.registration.microsoft.redirect-uri=https://amauta-test.lamolina.edu.pe/callback
spring.security.oauth2.client.registration.microsoft.client-authentication-method=post
spring.security.oauth2.client.registration.microsoft.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.microsoft.prompt=select_account

spring.security.oauth2.client.provider.microsoft.authorization-uri=https://login.microsoftonline.com/common/oauth2/v2.0/authorize
spring.security.oauth2.client.provider.microsoft.token-uri=https://login.microsoftonline.com/common/oauth2/v2.0/token
spring.security.oauth2.client.provider.microsoft.user-info-uri=https://graph.microsoft.com/oidc/userinfo
spring.security.oauth2.client.provider.microsoft.jwk-set-uri=https://login.microsoftonline.com/common/discovery/v2.0/keys
spring.security.oauth2.client.provider.microsoft.user-name=name

persistence:
#    jdbcUrl: jdbc:mysql://172.16.0.147/lamolina?autoReconnect=true&useSSL=false&serverTimezone=America/Lima
    jdbcUrl: jdbc:mysql://delfin-test.lamolina.edu.pe/lamolina?autoReconnect=true&useSSL=false
    showSql: false


despliegue:
    prospecto: prospecto2017g
    activo: false
    emails: bchapcha@lamolina.edu.pe rorihuela@lamolina.edu.pe
    copias: rorihuela@lamolina.edu.pe
    mailer: false
    lagunas: true
    storage: false
    tawkto: false
    sistema: 3
    ambiente: test

spring.rabbitmq.host: recauda-test.lamolina.edu.pe
spring.rabbitmq.username: lamolina
spring.rabbitmq.password: redhotchimichurri

# Microsoft Graph API - Teams Meetings
microsoft.graph.tenant-id=eeff3b89-2033-4ea4-8049-4bcf8822ec82
microsoft.graph.client-id=97ba2b79-26e7-4a4a-9c14-921ae45e4073
microsoft.graph.client-secret=aAv8Q~LSwhKQV-Ka.Or1BlKhfCSGEn5kKU2kEcvv

logging.file: /var/log/jenkins/lamolina-pivot.log
logging.level.pe.edu.lamolina: DEBUG
logging.level.pe.albatross.octavia: INFO
logging.level.pe.albatross.zelpers: DEBUG

#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
