
server.port: 80

#server.ssl.key-store: /lost+found/certificados/lamolina.store
#server.ssl.key-store-password: z3pp3l1n
#server.ssl.keyAlias: lamolina2018



oauth:
    google:
        callback: http://amauta-test.lamolina.edu.pe/callback
        key: 612109039547-a2nrlbq1s4cheeabprtb2hb1odkodcur.apps.googleusercontent.com
        secret: zAG0isrqVamwwRRlSjzx_SEi


persistence:
    jdbcUrl: jdbc:mysql://delfin-test.lamolina.edu.pe/lamolina?autoReconnect=true&useSSL=false
    userdb: thor
    password: redhotchimichurri
    showSql: true


despliegue:
    prospecto: prospecto2017g
    activo: false
    emails: rorihuela@lamolina.edu.pe
    copias: rorihuela@lamolina.edu.pe
    mailer: false
    lagunas: true
    s3: false
    tawkto: false
    sistema: 3
    ambiente: test

logging.file: /var/log/jenkins/lamolina-pivot.log
logging.level.pe.edu.lamolina: DEBUG
logging.level.pe.albatross.octavia: INFO

#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
