
server.port: 443

server.ssl.key-store: /lost+found/certificados/lamolina.store
server.ssl.key-store-password: z3pp3l1n
server.ssl.keyAlias: lamolina2018

#oauth:
#    google:
#        callback: https://amauta.lamolina.edu.pe/callback
#        key: 1098804607809-f8a85cpqdrvn7lajb7v5a1lucuegdst2.apps.googleusercontent.com
#        secret: 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

# Google OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id: 1098804607809-f8a85cpqdrvn7lajb7v5a1lucuegdst2.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret: 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
spring.security.oauth2.client.registration.google.redirect-uri: https://amauta.lamolina.edu.pe/callback
spring.security.oauth2.client.registration.google.scope: email,profile

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://openidconnect.googleapis.com/v1/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=email

# Microsoft Configuration
spring.security.oauth2.client.registration.microsoft.client-id=9cf62bf6-21db-4e25-bab6-5fa7518958f3
spring.security.oauth2.client.registration.microsoft.client-secret=ldZ8Q~GWaZHayv~9cxqPVarphe-3p-~3OaNaxaOH
spring.security.oauth2.client.registration.microsoft.scope=openid,email,profile
spring.security.oauth2.client.registration.microsoft.redirect-uri=https://amauta.lamolina.edu.pe/callback
spring.security.oauth2.client.registration.microsoft.client-authentication-method=post
spring.security.oauth2.client.registration.microsoft.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.microsoft.prompt=select_account

spring.security.oauth2.client.provider.microsoft.authorization-uri=https://login.microsoftonline.com/common/oauth2/v2.0/authorize
spring.security.oauth2.client.provider.microsoft.token-uri=https://login.microsoftonline.com/common/oauth2/v2.0/token
spring.security.oauth2.client.provider.microsoft.user-info-uri=https://graph.microsoft.com/oidc/userinfo
spring.security.oauth2.client.provider.microsoft.jwk-set-uri=https://login.microsoftonline.com/common/discovery/v2.0/keys
spring.security.oauth2.client.provider.microsoft.user-name=name


persistence:
    jdbcUrl: jdbc:mysql://delfin.lamolina.edu.pe/lamolina?autoReconnect=true&useSSL=false
    showSql: true


despliegue:
    prospecto: prospecto2017g
    activo: false
    emails: rorihuela@lamolina.edu.pe
    copias: hpc@lamolina.edu.pe rorihuela@lamolina.edu.pe
    mailer: true
    lagunas: false
    storage: true
    tawkto: false
    sistema: 3
    ambiente: prod

spring.rabbitmq.host: 172.16.0.111
spring.rabbitmq.username: lamolina
spring.rabbitmq.password: redhotchimichurri

logging.file: /var/log/jenkins/lamolina-pivot.log
logging.level.pe.edu.lamolina: DEBUG
