server.use-forward-headers=true

oauth:
    google:
        callback: http://amauta.lamolina.edu.pe/callback
        key: 612109039547-kpslatsrvja8s3ftl9ll2bcncjl9p7dc.apps.googleusercontent.com
        secret: i_Eh3sJ3yB9ujG9wZeXXQdJD


persistence:
    jdbcUrl: jdbc:mysql://delfin.albatross.pe/lamolina?autoReconnect=true&useSSL=false
    userdb: odin
    password: z3pp3l1nchimichurri
    showSql: false


despliegue:
    prospecto: prospecto2017g
    activo: false
    emails: lypagl@gmail.com bladymircch@gmail.com
    copias: lypagl@gmail.com
    mailer: true
    lagunas: false
    s3: true
    tawkto: true
    sistema: 3

logging.file: /var/log/jenkins/lamolina-pivot.log
logging.level.pe.edu.lamolina: DEBUG
