
#oauth:
#    google:
#        callback: http://localhost:9000/callback
#        key: 1098804607809-f8a85cpqdrvn7lajb7v5a1lucuegdst2.apps.googleusercontent.com
#        secret: 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

# Google OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id: 1098804607809-f8a85cpqdrvn7lajb7v5a1lucuegdst2.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret: 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
spring.security.oauth2.client.registration.google.redirect-uri: http://localhost:9000/callback
spring.security.oauth2.client.registration.google.scope: email,profile

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://openidconnect.googleapis.com/v1/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=email

# Microsoft Configuration
spring.security.oauth2.client.registration.microsoft.client-id=7031e4ec-2682-416b-ab9d-6950d4c57615
spring.security.oauth2.client.registration.microsoft.client-secret=bOs8Q~hIvMYSh4SOxoPqnThaHYMtBxENARwKCbsx
spring.security.oauth2.client.registration.microsoft.scope=openid,email,profile
spring.security.oauth2.client.registration.microsoft.redirect-uri=http://localhost:9000/callback
spring.security.oauth2.client.registration.microsoft.client-authentication-method=post
spring.security.oauth2.client.registration.microsoft.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.microsoft.prompt=select_account

spring.security.oauth2.client.provider.microsoft.authorization-uri=https://login.microsoftonline.com/common/oauth2/v2.0/authorize
spring.security.oauth2.client.provider.microsoft.token-uri=https://login.microsoftonline.com/common/oauth2/v2.0/token
spring.security.oauth2.client.provider.microsoft.user-info-uri=https://graph.microsoft.com/oidc/userinfo
spring.security.oauth2.client.provider.microsoft.jwk-set-uri=https://login.microsoftonline.com/common/discovery/v2.0/keys
spring.security.oauth2.client.provider.microsoft.user-name=name

#persistence:
#   jdbcUrl: jdbc:mysql://localhost/lamolina?autoReconnect=true&useSSL=false
#   userdb: root
#   password: mysql
#   showSql: false


persistence:
    jdbcUrl: jdbc:mysql://172.16.0.147/lamolina?autoReconnect=true&useSSL=false&serverTimezone=America/Lima
    userdb: thor
    password: redhot2023unalm
    showSql: false

despliegue:
    prospecto: prospecto2017g
    activo: false
    emails: bchapcha@lamolina.edu.pe rorihuela@lamolina.edu.pe
    copias: rorihuela@lamolina.edu.pe
    mailer: false
    lagunas: true
    storage: false
    tawkto: false
    sistema: 3
    ambiente: desa

spring.rabbitmq.host: 127.0.0.1
spring.rabbitmq.username: guest
spring.rabbitmq.password: guest

task:
    corePoolSize: 6
    threadName: Spring-Task-

logging.level.pe.edu.lamolina: DEBUG
logging.level.pe.albatross.zelpers: DEBUG
logging.level.pe.albatross.octavia: INFO

spring.resources.chain.cache:false
spring.thymeleaf.cache: false

#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
