spring.profiles.active: devel

server.session.timeout: 7200


oauth:
    google:
        api: pe.albatross.zelpers.security.oauth.Google2Api


spring.resources.chain.cache:false
spring.thymeleaf.cache: false



persistence:
    driver: com.mysql.jdbc.Driver
    dialect: org.hibernate.dialect.MySQLDialect
    model: pe.edu.lamolina.model
    minPool: 5
    maxPool: 15
    maxIddleTime: 20
    acquireIncrement: 3


spring.mail.host: smtp.mailgun.org
spring.mail.port: 465
spring.mail.username: no-responder@carrerasqueapasionan.pe
spring.mail.password: redhotchimichurri
spring.mail.properties.mail.smtp.ssl.enable: true

aws:
    s3-key: AKIAJEF2KQKQCRS5GQRA
    s3-secret: 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

task:
    corePoolSize: 3
    threadName: Spring-Task-


error:
    whitelabel:
        enabled: false


multipart.maxFileSize: 80MB
multipart.maxRequestSize: 80MB


logging.level.org.springframework.web: INFO
logging.level.org.hibernate: INFO
logging.level.pe.edu.lamolina: INFO


despliegue:
    activo: false
    mailer: false


spring.redis.database: 4
spring.redis.host: localhost
spring.redis.port: 6379

