spring.profiles.active: devel
server.port: 9000

spring.thymeleaf.cache: false
spring.resources.chain.cache:false

server.session.timeout: 7200


oauth:
    google:
        api: pe.albatross.zelpers.security.oauth.Google2Api


spring.resources.chain.cache:false
spring.thymeleaf.cache: false

persistence:
    driver: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQLDialect
    model: pe.edu.lamolina.model
    minPool: 5
    maxPool: 15
    maxIddleTime: 20
    acquireIncrement: 3


spring.mail.host: smtp.mailgun.org
spring.mail.port: 465
spring.mail.username: no-responder@mailing.albatross.pe
spring.mail.password: 22fec5422d616128ff8ec99a20bab1c1-2b778fc3-9f8ed04f
spring.mail.properties.mail.smtp.ssl.enable: true


swift.auth-api: http://cdn.lamolina.edu.pe:5000/v3
swift.user: admin
swift.pass: 85e05c71378e448d
swift.domain: default
swift.project: 90afa410262f41f1af475ed599eeb798
swift.url-base: https://cdn.lamolina.edu.pe/v1/AUTH_90afa410262f41f1af475ed599eeb798/


task:
    corePoolSize: 6
    threadName: Spring-Task-


multipart.maxFileSize: 80MB
multipart.maxRequestSize: 80MB

despliegue:
    activo: false
    mailer: false
    usuarioSistema: SISTEMA


spring.redis.database: 4
spring.redis.host: localhost
spring.redis.port: 6379
