
oauth:
    google:
        callback: http://localhost:9000/callback
        key: 1098804607809-f8a85cpqdrvn7lajb7v5a1lucuegdst2.apps.googleusercontent.com
        secret: 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

persistence:
   jdbcUrl: jdbc:mysql://localhost/lamolina?autoReconnect=true&useSSL=false
   userdb: root
   password: mysql
   showSql: false


#persistence:
#    jdbcUrl: jdbc:mysql://172.16.0.147/lamolina?autoReconnect=true&useSSL=false&serverTimezone=America/Lima
#    userdb: thor
#    password: redhotchimichurri
#    showSql: true

despliegue:
    prospecto: prospecto2017g
    activo: false
    emails: bchapcha@lamolina.edu.pe rorihuela@lamolina.edu.pe
    copias: rorihuela@lamolina.edu.pe
    mailer: false
    lagunas: true
    storage: false
    tawkto: false
    sistema: 3
    ambiente: desa

task:
    corePoolSize: 6
    threadName: Spring-Task-

logging.level.pe.edu.lamolina: DEBUG
logging.level.pe.albatross.zelpers: DEBUG
logging.level.pe.albatross.octavia: INFO

spring.resources.chain.cache:false
spring.thymeleaf.cache: false

#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
