server.port: 9900

oauth:
    google:
        callback: http://localhost:9900/callback
        key: 612109039547-a2nrlbq1s4cheeabprtb2hb1odkodcur.apps.googleusercontent.com
        secret: zAG0isrqVamwwRRlSjzx_SEi


persistence:
    jdbcUrl: jdbc:mysql://localhost/agraria?autoReconnect=true&useSSL=false
    userdb: root
    password: mysql
    showSql: true


despliegue:
    prospecto: prospecto2017g
    activo: false
    emails: bladymir@albatross.pe bladymir@albatross.pe
    copias: bladymir@albatross.pe bladymir@albatross.pe
    mailer: false
    lagunas: true
    s3: true
    tawkto: false


logging.level.pe.edu.lamolina: DEBUG
#logging.level.pe.albatross.octavia: DEBUG

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
